package com.chinasoft.oaspringboot.Mapper;

import com.chinasoft.oaspringboot.entity.User;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tb
     *
     * @mbggenerated Tue Sep 24 14:51:35 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tb
     *
     * @mbggenerated Tue Sep 24 14:51:35 CST 2019
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tb
     *
     * @mbggenerated Tue Sep 24 14:51:35 CST 2019
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tb
     *
     * @mbggenerated Tue Sep 24 14:51:35 CST 2019
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tb
     *
     * @mbggenerated Tue Sep 24 14:51:35 CST 2019
     */
    int updateByPrimaryKey(User record);

    User loginByUser(@Param("name") String name,@Param("password") String password);
}