package com.chinasoft.oaspringboot.entity;

import java.io.Serializable;

public class User implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tb.id
     *
     * @mbggenerated Tue Sep 24 14:51:35 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tb.name
     *
     * @mbggenerated Tue Sep 24 14:51:35 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tb.password
     *
     * @mbggenerated Tue Sep 24 14:51:35 CST 2019
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tb.id
     *
     * @return the value of user_tb.id
     *
     * @mbggenerated Tue Sep 24 14:51:35 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tb.id
     *
     * @param id the value for user_tb.id
     *
     * @mbggenerated Tue Sep 24 14:51:35 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tb.name
     *
     * @return the value of user_tb.name
     *
     * @mbggenerated Tue Sep 24 14:51:35 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tb.name
     *
     * @param name the value for user_tb.name
     *
     * @mbggenerated Tue Sep 24 14:51:35 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tb.password
     *
     * @return the value of user_tb.password
     *
     * @mbggenerated Tue Sep 24 14:51:35 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tb.password
     *
     * @param password the value for user_tb.password
     *
     * @mbggenerated Tue Sep 24 14:51:35 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", password='" + password + '\'' +
                '}';
    }
}